#!/bin/sh

TEST_CODE=gifshuffle-test.c
TEST_PROG=gifshuffle-test

gcc $TEST_CODE -o $TEST_PROG -I../src/include -I../src/libstego/include -I../src/libstegofile/include -L../src/libstego -L../src/libstegofile -lsndfile -lpng -ljpeg -lgif -lstego -lstegofile

LD_LIBRARY_PATH=../src/libstegofile:../src/libstego ./$TEST_PROG
