#!/bin/sh

TEST_CODE=pq-embed-test.c
TEST_PROG=pq-embed-test

gcc $TEST_CODE -o $TEST_PROG -I../src/include -I../src/libstego/include -I../src/libstegofile/include -L../src/libstego -L../src/libstegofile -lsndfile -lpng -ljpeg -lgif -lstego -lstegofile

LD_LIBRARY_PATH=../src/libstegofile:../src/libstego ./$TEST_PROG


TEST_CODE=pq-extract-test.c
TEST_PROG=pq-extract-test

gcc $TEST_CODE -o $TEST_PROG -I../src/include -I../src/libstego/include -I../src/libstegofile/include -L../src/libstego -L../src/libstegofile -lsndfile -lpng -ljpeg -lgif -lstego -lstegofile

LD_LIBRARY_PATH=../src/libstegofile:../src/libstego ./$TEST_PROG
